### ISSUE TITLE
Better Cast Text

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-rf6#100]
For the Public Text here:

<img width="587" alt="Screenshot 2024-11-01 at 5 35 39 PM" src="https://github.com/user-attachments/assets/b1f615ac-898f-46da-847b-d095acbdf4bc">

Can we change:

```
I just delegated on @pairwise for Retro Funding 6 Governance Leadership to @brichis.
```

to 

```
I just delegated on @pairwise's Liquid Democracy Experiment.

I chose @brichis to vote (or delegate) for me in the Governance Leadership category of @optimism's RF6. 

You can try it out too!

https://app.pairwise.vote/
```

**Comment by MoeNick** [comment]
Hey @HrithikSampson 
Can you do it please. Its at the end of delegate flow.

**Comment by RamRamez** [comment]
Done!
It's waiting for review.

**Comment by MoeNick** [comment]
@mmahdigh did it merge into prod?

**Comment by mmahdigh** [comment]
Yes.
