### ISSUE TITLE
Changing some of the text for the Delegate to Farcaster handle discovery modal

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-rf6#102]
<img width="271" alt="Screenshot 2024-11-01 at 6 00 36 PM" src="https://github.com/user-attachments/assets/a00cd3a9-623f-4e78-a2ef-e81ef1e23a60">
<img width="1102" alt="Screenshot 2024-11-01 at 6 00 55 PM" src="https://github.com/user-attachments/assets/4744df69-9552-4e8a-9ec4-6840e0e7a990">

Small changes to this text:
```
Delegate on Farcaster
Delegating for
Governance Analytics decision to someone you trust

Enter username or paste profile link to delegate voting power to someone on Farcaster
@cerv1 {User profile picture}  is available on Faracster
```

to 

```
Delegate with Farcaster
Delegating for
Governance Analytics category

Enter a username or paste a profile link to delegate your voting power to someone you trust

@cerv1 {User profile picture} on Farcaster
```
I changed:
1. "on" to "with"
2. "decision to someone you trust" to "category"
3. added "your" and changed "on Farcaster" for "you trust"
4. changed "is available on Faracster" to "on Farcaster" fixing a typo

**Comment by RamRamez** [comment]
Done! (it's waiting for code review)
