### ISSUE TITLE
Add COI in edit vote view

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rf6#104]
As a user, I want to report the conflict of interest if I've forgotten in pairwise flow. 

Design:
https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2183-86142&t=rgErpVt0MnQjS31Y-1
![Image](https://github.com/user-attachments/assets/0d685c41-e1ed-4726-af65-92ef3a4bb5f3)

Success Criteria:

- [ ] it is an icon beside the percentages. 
- [ ] On hover change the color of the icon to read
- [ ] When clicked it goes at the button and ou of the edit view, the percentage of this CIO will be distributed to other projects based on their wights
- [ ] The user has an option to undo the marked CIO, when clicked it puts the project into the list again with 0 percentages.

**Comment by MoeNick** [comment]
@markoprljic @Ayaz1997 Number 3 and 4 of the acceptance criteria of this issue is pending by design.

**Comment by Meriem-BM** [comment]
Hey @MoeNick, what about ranking, should be locked?

**Comment by maryjaf** [comment]
i haven't seen the COI projects in this list @HrithikSampson 

https://github.com/user-attachments/assets/4d9d3bae-7b6e-4fdf-ab6c-05dba15ff8cf

**Comment by MoeNick** [comment]
See this design @Meriem-BM @maryjaf 
https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2278-52415&t=W3ivo43WNQUzuFMv-4

Yes if user removes it, it drops to the end of table (actually in another table) and teh percentages and ranking should be without this project.

**Comment by Meriem-BM** [comment]
@maryjaf, can you test this please

**Comment by Meriem-BM** [comment]
> please take a look on below screen record
> 
> this message is shown "At least two projects must be unlocked" although my projects is unlocked
> 
> https://github.com/user-attachments/assets/a85d634a-6274-474d-bf1a-fdc0bfa2a971 @Meriem-BM

Thanks, made a fix, if you can test again

**Comment by maryjaf** [comment]
> please take a look on below screen record
> 
> this message is shown "At least two projects must be unlocked" although my projects is unlocked
> 
> https://github.com/user-attachments/assets/a85d634a-6274-474d-bf1a-fdc0bfa2a971 [@Meriem-BM](https://github.com/Meriem-BM)

thanks @Meriem-BM this issue has been fixed 

but there is another problem I'm not sure it is exactly related to this issue or not ? please take a look on below screen record 

https://github.com/user-attachments/assets/68d25d1f-9619-42a3-a4ce-2cd2f1f8c11b

when I tap on conflict icon in edit page the percentage of locked projects are changed also @Meriem-BM

**Comment by Meriem-BM** [comment]
Thanks for catching that, made a fix if you can check

**Comment by maryjaf** [comment]
thanks @Meriem-BM It has been fixed
