### ISSUE TITLE
Add a Farcaster cast after user attestation. 

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-rf6#109]
### Design:
https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2290-89088&t=Fp3yTlMadXVi0DGb-1

### While someone is submitting their vote, we should have a Farcaster prompt so they can advertise themselves as someone to delegate to

After someone has done the pairwise ranking and edited their %s and then they click the submit ballot button... They should see a modal promting them to make a cast to promote themselves as a delegate, like this one: 

<img width="445" alt="Screenshot 2024-11-04 at 8 20 33 AM" src="https://github.com/user-attachments/assets/44f8e5f8-c460-40f2-bea0-ad4f85a298cb">

It should be a modal like that except it should have different text:

The header:

Successfully voted in 

[{Category Name}]

Would you like to receive more delegations in our liquid democracy experiment?

The cast text:

I voted in @pairwise's Liquid democracy experiment, ranking the [{Category Name}] category of @optimism's RF6.

Delegate to me here:

https://app.pairwise.vote/

**Comment by MoeNick** [comment]
![Image](https://github.com/user-attachments/assets/0d90ab48-0463-4d7e-9e38-cd6d990c7d41)
@markoprljic

**Comment by markoprljic** [comment]
See here @MoeNick https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2290-89088&t=Fp3yTlMadXVi0DGb-1

**Comment by markoprljic** [comment]
I'm seeing this in production but ....
![Image](https://github.com/user-attachments/assets/87ef4e0b-dbf5-4058-993e-c37ded5fd8bb)

When I click on Post on Farcaster it does not get transferred to Draft post message...
 ![Image](https://github.com/user-attachments/assets/a2b36da6-64f6-4cec-a8f2-b19e0930a6ed)

What's the status of this issue?

**Comment by HrithikSampson** [comment]
@maryjaf , it is ready to be tested

**Comment by HrithikSampson** [comment]
> I'm seeing this in production but .... ![Image](https://private-user-images.githubusercontent.com/5704285/384910819-87ef4e0b-dbf5-4058-993e-c37ded5fd8bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNjQwNDcsIm5iZiI6MTczMTM2Mzc0NywicGF0aCI6Ii81NzA0Mjg1LzM4NDkxMDgxOS04N2VmNGUwYi1kYmY1LTQwNTgtOTkzZS1jMzdkZWQ1ZmQ4YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMjIyMjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjRhYzM0MDlmOTM5Mzg3NWIxNTI4ZWE4YjA5ZTNlMTA2MTEzZTg1ODFjODE4MWJmMDVjOTY5Yzg1ODA3NDVjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Sl0w0-sNKKfXOPPSDL-9-_xx3HkoUbR3BW5V5-roV0k)
> 
> When I click on Post on Farcaster it does not get transferred to Draft post message... ![Image](https://private-user-images.githubusercontent.com/5704285/384911119-a2b36da6-64f6-4cec-a8f2-b19e0930a6ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNjQwNDcsIm5iZiI6MTczMTM2Mzc0NywicGF0aCI6Ii81NzA0Mjg1LzM4NDkxMTExOS1hMmIzNmRhNi02NGY2LTRjZWMtYThmMi1iMTllMDkzMGE2ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMjIyMjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzcyZDQwYTc2MDNkNGE5NjcwN2M0YjVlMzQyMzI3OGJlZWIxYThlZjA0NzE2Yjc1OWZmMzNjNWM1MjgyNjRhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.e8r4TVk4XC6WsEz9ohvvuduZzxZGoVq_lSXp0Jkvknc)
> 
> What's the status of this issue?

I think it is the delegation flow, this issue is different, i can change this text if you want.

**Comment by maryjaf** [comment]
There are some problems 

1-when I tap on post on farcaster when I back to pairwise app this modal is still open
2- this modal is shown for multiple time after I posted on farcaster , is it expected result? 
please check below screen record 
 

https://github.com/user-attachments/assets/2580dd47-1863-43a1-9586-d08b6c9b341a

@HrithikSampson @MoeNick @markoprljic

**Comment by MoeNick** [comment]
It's expected @maryjaf 
User has to click on Next, 
But good catch for better UX if we can do it by a web service, we can keep this issue in backlog for the improvements.

**Comment by markoprljic** [comment]
> I think it is the delegation flow, this issue is different, i can change this text if you want.

You're right @HrithikSampson nevermind.

**Comment by HrithikSampson** [comment]
@maryjaf , it is ready to be tested

**Comment by maryjaf** [comment]
> 1- I can't submit vote to test this [@HrithikSampson](https://github.com/HrithikSampson) [@mmahdigh](https://github.com/mmahdigh)

2-  I try with another user, the below modal is shown, I think when I tap on copy icon sothing should be shown that it is copied

https://github.com/user-attachments/assets/d556af9a-53c8-4a08-91c9-8729d6ffd2f9

**Comment by maryjaf** [comment]
4- what should happen by tapping on close?the user should be stay in this page or should be redirected to allocation page ?

https://github.com/user-attachments/assets/36974f8c-1e3f-4948-96be-867cfb7530aa

**Comment by HrithikSampson** [comment]
> > 1- I can't submit vote to test this [@HrithikSampson](https://github.com/HrithikSampson) [@mmahdigh](https://github.com/mmahdigh)
> 
> 2- I try with another user, the below modal is shown, I think when I tap on copy icon sothing should be shown that it is copied 3- it seems the size of modal isn't ok
> 
>  Screen.Recording.2024-11-14.at.10.09.41.AM.mov

@maryjaf , please could you check this I think this point is resolved

**Comment by HrithikSampson** [comment]
> 4- what should happen by tapping on close?the user should be stay in this page or should be redirected to allocation page ?
> 
>  Screen.Recording.2024-11-14.at.12.08.46.PM.mov

cc: @MoeNick

**Comment by maryjaf** [comment]
> > > 1- I can't submit vote to test this [@HrithikSampson](https://github.com/HrithikSampson) [@mmahdigh](https://github.com/mmahdigh)
> > 
> > 
> > 2- I try with another user, the below modal is shown, I think when I tap on copy icon sothing should be shown that it is copied 3- it seems the size of modal isn't ok
> > Screen.Recording.2024-11-14.at.10.09.41.AM.mov
> 
> @maryjaf , please could you check this I tried to resolve these 2 points



> 1- I can't submit vote to test this @HrithikSampson @mmahdigh
> 
>  Screen.Recording.2024-11-13.at.4.25.29.PM.mov

I got this error again and I couldn't complete the flow for testing 

https://github.com/user-attachments/assets/981be2c6-9a74-4190-9db6-5267cf5fb1a3

**Comment by markoprljic** [comment]
4- what should happen by tapping on close?the user should be stay in this page or should be redirected to allocation page ?

Stay on the same page @maryjaf

**Comment by maryjaf** [comment]
Do you mean the current behavior is okay? @markoprljic 
But if the user stays on the same page, the "Submit Vote" button remains enabled, and they might tap it again.
Is this okay?

**Comment by markoprljic** [comment]
Ah yes, sorry, this is AFTER attestation. What Moenick said is correct. We can redirect user back to main page and mark the category as ranked. 

In case of Badgeholders, we show them Submit Ballot modal after this attestation.

**Comment by HrithikSampson** [comment]
> 4- by tapping close, user will be redirected to categories page, making the category marked as voted.
> 
> @HrithikSampson @maryjaf
> 
> It should be the same with currant flow we have in close after attestation. Take a look at what we did right now and only change the required things.

@maryjaf , this point is ready to be tested

**Comment by maryjaf** [comment]
Thanks @HrithikSampson all problems have been fixed
