### ISSUE TITLE
[Griffs feedback] Changes on Splash page

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/pairwise-rf6#111]

**Comment by markoprljic** [comment]
https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=1763-120596&t=TFoIin9il128HyXW-1

**Comment by markoprljic** [comment]
Ready for review https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=1763-120596&t=Fp3yTlMadXVi0DGb-1

**Comment by markoprljic** [comment]
@HrithikSampson https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2411-90262&t=6EI1YJtqaVKTzqKO-1

**Comment by HrithikSampson** [comment]
@maryjaf , it is ready to be tested

**Comment by maryjaf** [comment]
there is a auto scroll logic to top of the page @HrithikSampson 

https://github.com/user-attachments/assets/4da72b52-cc10-47a2-ab80-4de9538ea19e

**Comment by MoeNick** [comment]
Is it merged on staging? @HrithikSampson @mmahdigh

**Comment by HrithikSampson** [comment]
@maryjaf , it is ready to be tested.
@Moenick, just merged

**Comment by maryjaf** [comment]
> there is a auto scroll logic to top of the page [@HrithikSampson](https://github.com/HrithikSampson)
> 
>  Screen.Recording.2024-11-12.at.3.16.25.PM.mov

The problem has been fixed , thanks
