### ISSUE TITLE
[Griff's feedback] For badgholders: Show modal on categories page and add update ballot to success attestation. 

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/pairwise-rf6#112]
- [ ] Modal for guiding bagholders from categories page: https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2244-85883&t=Fp3yTlMadXVi0DGb-1 (it's the high fidelity link @markoprljic )
![Image](https://github.com/user-attachments/assets/cba1917a-1008-4efb-be3c-9665841b6442)

**Comment by markoprljic** [comment]
Ready for review https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2244-85883&t=Fp3yTlMadXVi0DGb-1

**Comment by MoeNick** [comment]
@Meriem-BM please take a look.
The second to-do item  might be done by @HrithikSampson , the difference is if we detect user is bagholder we should have that button after success attestation and farcast suggestion. Please double check with @Meriem-BM

**Comment by Meriem-BM** [comment]
Hey @maryjaf this is ready for test, thanks

**Comment by Meriem-BM** [comment]
> There is a problem related to login with email , when I got an error in connecting email flow, by closing the modal i can continue ranking
> 
> please take a look on below screen record : @Meriem-BM https://github.com/user-attachments/assets/3eef9b1c-8414-4875-aef0-e62c743a53f3

Thanks, made a fix, if you can check

**Comment by maryjaf** [comment]
I've tested again, but by closing the below modal , I can continue voting 

![image](https://github.com/user-attachments/assets/fb1aa649-c25d-406e-9736-fd36d918cb0a)


https://github.com/user-attachments/assets/55f3b797-8282-474a-b9a1-fb948fb4023d


@Meriem-BM

**Comment by Meriem-BM** [comment]
> I've tested again, but by closing the below modal , I can continue voting

Thanks, made a fix if you can test again

**Comment by maryjaf** [comment]
Thanks, @Meriem-BM!
Currently, users are unable to close this modal, and there's no option to navigate back to the allocation page or the connect email modal. This feels like a UX issue that needs to be addressed. What are your thoughts, @MoeNick @markoprljic ? 


https://github.com/user-attachments/assets/7858b9a8-7b44-4e5a-8f66-59e21d326960

**Comment by markoprljic** [comment]
That X button should work and when you click on it you should be able to land back where you came from.

**Comment by Meriem-BM** [comment]
Can you test this @maryjaf

**Comment by maryjaf** [comment]
Thanks @Meriem-BM it works correctly
If user select a wrong email, they can close the modal by tapping on close icon, and the connect email modal will repon by tapping on any button in ranking page 

this is new behavior, is this acceptedin point of your view? @MoeNick @markoprljic 

https://github.com/user-attachments/assets/d00c1182-62e0-4f03-8640-ee7a14be0584
