### ISSUE TITLE
[Griff's feedback] After updating ballot, letting badgholders know to do the budget on voting app.

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/pairwise-rf6#113]

**Comment by markoprljic** [comment]
Updated here https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2244-87246&t=Fp3yTlMadXVi0DGb-1

**Comment by HrithikSampson** [comment]
@maryjaf , ready to be tested

**Comment by maryjaf** [comment]
Thanks @HrithikSampson 

![Image](https://github.com/user-attachments/assets/28b61845-f562-4fb4-872f-a3499693ddbd)

**Comment by HrithikSampson** [comment]
@maryjaf , it is ready to be tested repushed it after reverting it back

**Comment by maryjaf** [comment]
Thanks @HrithikSampson 
![Image](https://github.com/user-attachments/assets/475d7cf5-3c51-440f-a4cc-f905200a737e)
![Image](https://github.com/user-attachments/assets/68e6d014-79d4-484f-9213-e8fee46f3ed7)
