### ISSUE TITLE
Mobile view detection

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/pairwise-rf6#120]
When user is on mobile we should detect and show them info screen as per design below. 

![Image](https://github.com/user-attachments/assets/1fecddd1-f8b5-4622-a362-7812942bf83d)

Figma design source https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=1038-106617&t=BDmiuv4MZhTQpiL8-1

**Comment by HrithikSampson** [comment]
@maryjaf , I have merged on staging, It is ready to be tested.

**Comment by maryjaf** [comment]
![IMG_5542](https://github.com/user-attachments/assets/b8be3092-3054-4121-af2a-46ea985ea15f)
Thanks @HrithikSampson now this page is shown when I check staging on mobile 
One question, by tapping on ok I see below screen record , is this the expected result?

https://github.com/user-attachments/assets/9789003e-5251-4a29-bd37-daaf6efbe857

**Comment by HrithikSampson** [comment]
> ![IMG_5542](https://private-user-images.githubusercontent.com/111529185/384657529-b8be3092-3054-4121-af2a-46ea985ea15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTk4MzgsIm5iZiI6MTczMTIxOTUzOCwicGF0aCI6Ii8xMTE1MjkxODUvMzg0NjU3NTI5LWI4YmUzMDkyLTMwNTQtNDEyMS1hZjJhLTQ2ZWE5ODVlYTE1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNjE4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmY3M2NjZTNiYzA4ZmIyZmU1MjIwOGE1NmEzYmU5Mzk4YTg2YWU5ZGUzZjRmN2UwMjEzMWFlNTJhMGExNDg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rERfBSfYaqKTyxD4xlCP-WqC4ggW3kXvri_MNXynvNY) Thanks @HrithikSampson now this page is shown when I check staging on mobile One question, by tapping on ok I see below screen record , is this the expected result?
> 
>  ScreenRecording_11-10-2024.07-35-34_1.mp4

cc: @markoprljic @MoeNick

**Comment by markoprljic** [comment]
No, actually there shouldn't be an ok button. Please remove it. Apologies
for the confusion.

**Comment by maryjaf** [comment]
Because today was your offday and there was no risk in removing this button, I made this change and I remove Ok button in mobile view@HrithikSampson
