### ISSUE TITLE
Submit Attestation after Edit - does not work

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-rf6#129]
When I go to Edit category and want to submit attestation again, the button quickly shows loading and nothing happens afterwards. 

https://github.com/user-attachments/assets/d023c6b5-07a7-45bd-a300-b43181eab6c1

**Comment by maryjaf** [comment]
I tried to reproduce but I couldn't 

- I tap on edit 
- change some percentages 
- tap on submit vote 
- I edit and submit my vote successfully
 
- https://github.com/user-attachments/assets/8d983d27-1319-4e26-aebd-37fcd7f477a1

**Comment by MoeNick** [comment]
@mmahdigh it's so similar with the problem @GriffGreen had, 
Did you guys reproduce it?

**Comment by maryjaf** [comment]
> I tried to reproduce but I couldn't
> 
> * I tap on edit
> * change some percentages
> * tap on submit vote
> * I edit and submit my vote successfully
> * Screen.Recording.2024-11-11.at.7.50.14.PM.mov

I retested and it works fine for me, maybe there is a specific scenario I'll check more 


https://github.com/user-attachments/assets/99c92ddb-a7eb-4552-8536-b22181f46b5d

**Comment by markoprljic** [comment]
I'm running on Brave browser Version 1.70.126 Chromium: 129.0.6668.100 (Official Build) (arm64)

**Comment by maryjaf** [comment]
thanks @markoprljic 
this problem happens on brave and it works fine on chrome 
 @mmahdigh 

https://github.com/user-attachments/assets/b584a11f-5ab4-448d-aecf-ca691796b4d2

**Comment by MoeNick** [comment]
@mmahdigh could you do investigations on this?

**Comment by mmahdigh** [comment]
I can't reproduce it on Brave. Is there any chance you're using a particular extension that could be blocking some of the outbound requests? @maryjaf @markoprljic

**Comment by maryjaf** [comment]
this is the console log:

![image](https://github.com/user-attachments/assets/36c8bacd-860e-404f-8632-51c8c516dc32)

**Comment by mmahdigh** [comment]
> this is the console log:
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/386112811-36c8bacd-860e-404f-8632-51c8c516dc32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzQ1MjgsIm5iZiI6MTczMTU3NDIyOCwicGF0aCI6Ii8xMTE1MjkxODUvMzg2MTEyODExLTM2YzhiYWNkLTg2MGUtNDA0Zi04NjMyLTUxYzhjNTE2ZGMzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwODUwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTM2ZTVhNTY2NDE5Y2Q5MzM3YTA3M2M1YjkzN2RkMDcwNGI5ZmFiOTVlOGY1N2M0OTU1OWI1ZWQyN2FlOTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gPCFLnEC3cyC2H33tjlDUajVp--0Mpt76baKBH0daJ0)

Thanks! Could you give it another try now and post your console?

**Comment by maryjaf** [comment]
no change ! 

https://github.com/user-attachments/assets/756431d7-5975-4a9e-8ff3-d4ee32b32a31

Now I see this error on chrome also 


https://github.com/user-attachments/assets/721dc30a-cbbf-4144-9c83-48ec8c4d052d

0x523E41A134Ab0999F2dC844eA02d9b53cC28fD1a

**Comment by mmahdigh** [comment]
> no change !
> 
>  Screen.Recording.2024-11-14.at.1.24.12.PM.mov 
> Now I see this error on chrome also
> 
>  Screen.Recording.2024-11-14.at.1.25.53.PM.mov 
> 0x523E41A134Ab0999F2dC844eA02d9b53cC28fD1a

Please use the prod app as the first image was on prod. (Added a line just on prod)

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/70b870b4-93eb-46af-844f-7dfee07ed1b5)

@mmahdigh

**Comment by mmahdigh** [comment]
> ![image](https://private-user-images.githubusercontent.com/111529185/386160292-70b870b4-93eb-46af-844f-7dfee07ed1b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODMzNjEsIm5iZiI6MTczMTU4MzA2MSwicGF0aCI6Ii8xMTE1MjkxODUvMzg2MTYwMjkyLTcwYjg3MGI0LTkzZWItNDZhZi04NDRmLTdkZmVlMDdlZDFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxMTE3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGYwNGU1MTc2OGE2NGZlOWRkMjcxYjVmOTE4MjNjODQzOTdjZmM5MmU1ZDExNjJjYzE2NjczMzg2ZjQ2ZGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3tvQMNshL08lhiuJLIxUEMJRDL5jIrSMWMv71uRiz3E)
> 
> @mmahdigh

@Meriem-BM Do you check if the user has an active thirdweb smart wallet before letting them go to the edit page?

As you can see in the pic, @maryjaf is trying to `submit vote` but doesn't have a wallet/signer.

**Comment by Meriem-BM** [comment]
> @Meriem-BM Do you check if the user has an active thirdweb smart wallet before letting them go to the edit page?
> 
> As you can see in the pic, @maryjaf is trying to `submit vote` but doesn't have a wallet/signer.

No, I'll make a fix

**Comment by maryjaf** [comment]
By tapping on edit the edit page is shown , but by tapping on the vote button the connect email modal is shown , it seems this is  the root cause of the problem, the smart wallet isn't checked in edit flow

https://github.com/user-attachments/assets/4d60106f-f0c9-432e-95a8-a5bed560503c

**Comment by maryjaf** [comment]
Thanks Guys, this problem has been fixed
