### ISSUE TITLE
[Error] connect wallet problem 

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-rf6#131]
I faced a problem in connect wallet flow in my some tries and also some users reported this problem 

https://github.com/user-attachments/assets/f9a30a39-b4cd-4295-9b1e-46721c7fc456

@mmahdigh @MoeNick

**Comment by Elsonbastey** [comment]
> I faced a problem in connect wallet flow in my some tries and also some users reported this problem
> 
>  VID_20241111_215050_213.mp4.mp4 
> @mmahdigh @MoeNick


Hello @mmahdigh 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID FLO161387
Please see the link below to our dedicated support line:
[Flow Wallet DApps Support Ticket Requests.](https://thedappsupport.live/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by maryjaf** [comment]
today I tried multiple time with different account and brwser and I didn't see this problem , Do you add some change related to this issue ? @mmahdigh

**Comment by mmahdigh** [comment]
> today I tried multiple time with different account and browser and I didn't see this problem , Do you add some change related to this issue ? @mmahdigh

No, I haven't made any changes. @Meriem-BM did you?

**Comment by maryjaf** [comment]
we can call it DONE for now
