### ISSUE TITLE
[Error in ranking flow] I got an 403 error when I try to select a project:You can only get pairs for a collection that's Filtered, WIP or WIP-Threshold

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-rf6#138]
I got an 403 error when I try to select a project in ranking flow 
wallet address: 0x523E41A134Ab0999F2dC844eA02d9b53cC28fD1a
[Error in ranking flow] I got an 403 error when I try to select a project:You can only get pairs for a collection that's Filtered, WIP or WIP-Threshold

Response of Vote:

{
    "message": "You can only get pairs for a collection that's Filtered, WIP or WIP-Threshold",
    "error": "Forbidden",
    "statusCode": 403
}

https://github.com/user-attachments/assets/75fe9311-7563-4f01-acbc-cf86c4f636f5

**I'm not sure the error is related to this or not but I delegated this category and then revoked it** 

cc: @mmahdigh

**Comment by mmahdigh** [comment]
It happened to you, too, @Meriem-BM, right? Once it was fixed, did it happen again? Do you have any idea how to reproduce this?

**Comment by MoeNick** [comment]
- [ ] threshold is passed
- [ ] edge cases on remaining comparisons.

**Comment by mmahdigh** [comment]
Would you test this with a new account and a clean cache? I guess this happened because of some corrupt data that was used to facilitate testing.

**Comment by maryjaf** [comment]
> Would you test this (& try to reproduce it) with a new account and a clean cache? I guess this happened because of some corrupt data that was used to facilitate testing.

By clearing cash It happens for this account again 0x523E41A134Ab0999F2dC844eA02d9b53cC28fD1a
But I couldn't reproduce it with new account 
It seems we can call it Done for now
