### ISSUE TITLE
Copy chnages

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/pairwise-rf6#141]
![Image](https://github.com/user-attachments/assets/128750c2-ac78-404c-b241-57e8b5338c5d)

![Image](https://github.com/user-attachments/assets/9d3d6ae8-9b44-4bf8-8c95-cf0b2308db29)

![Image](https://github.com/user-attachments/assets/33ff8bb6-2401-41e7-857f-62fb54d45208)

**Comment by HrithikSampson** [comment]
@maryjaf , it is ready to be tested
