### ISSUE TITLE
[Error] number of delegation for each category or budget allocation isn't shown

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-rf6#156]
as you can see in below screen record "some one delegated to me", but in category or budget allocation  this copy isn't shown "1 people degated to you" like as before

![image](https://github.com/user-attachments/assets/4738bde6-6cc3-4eee-a1ba-f9952a15abf5)

wallet address: 0x523E41A134Ab0999F2dC844eA02d9b53cC28fD1a
 cc: @mmahdigh

**Comment by mmahdigh** [comment]
Could you take a look, please? @HrithikSampson

**Comment by HrithikSampson** [comment]
@maryjaf , I think the copy was changed.
cc: @MoeNick

**Comment by MoeNick** [comment]
Someone delegated to you is correct in the matter of the copy. 
In the @maryjaf experience, we don't show the deleted number of persons, when the category is voted. 

The copy of `voted` should change to: `Voted on behalf of {Delegetedpersons] persons` 
NOTE: if it's only one person, the copy will be person not persons. (remove the s) 

@HrithikSampson @maryjaf

**Comment by HrithikSampson** [comment]
@maryjaf , it is ready to be tested.

**Comment by maryjaf** [comment]
Thanks @HrithikSampson 
A space between and 1 is required.

![image](https://github.com/user-attachments/assets/630573d3-a774-490e-bd19-8fe0a83ecfe9)

and could you please delegate to me "maryjaf" on budget, Governance Leadership  and Governance Analytic categories for more testing

**Comment by HrithikSampson** [comment]
@maryjaf , delegated to you and added space

**Comment by maryjaf** [comment]
everything related to delegation  in category list is shown correctly, thanks @HrithikSampson 

![image](https://github.com/user-attachments/assets/7c27b5f4-c670-4e2e-af93-e7c7d8471a5d)

Only one question how can I be sure 4 people delegated to me 

![image](https://github.com/user-attachments/assets/d0c90a72-0224-4194-ab89-9160ee77edb4)

**Comment by HrithikSampson** [comment]
I think that 4 people is like the unique addresses that delegated to you,
I had delegated from 3 different wallets because in some I had already voted in one or 2 categories.

I am not sure how to be sure about it. 

cc: @mmahdigh @MoeNick

**Comment by maryjaf** [comment]
Thanks , based on this 4 is correct because one person delegated to me before
