### ISSUE TITLE
Changes on side panel

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rf6#169]
As a user, I want to see a report an issue and a feedback button visible on the main page at the side panel

![Image](https://github.com/user-attachments/assets/36ce752d-7293-4d0d-90ed-13db5594f361)

### Design:
https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2964-47294&t=tnOSvUJNakyD19lA-4

### Accetance Criteria

- [x] Removing the feedback link from the updated ballot flow. 
- [ ] Sidebar should have a title as described in Figma
- [x] 2 buttons added to the sidebar

**Comment by HrithikSampson** [comment]
this issue is ready to be tested

**Comment by maryjaf** [comment]
> * [ ]  Sidebar should have a title as described in Figma

the title should be changed based on figma @HrithikSampson 

![Image](https://github.com/user-attachments/assets/1bde1e90-fd0f-42f8-b159-f26bf0c9cc5e)

**Comment by HrithikSampson** [comment]
Sometimes it is different i think @maryjaf 
https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2961-79133&t=1qCRhTsNyoIbOoAu-0

**Comment by HrithikSampson** [comment]
Like when there is some delegation on the Account it is You have extra powers now! I think

**Comment by maryjaf** [comment]
> Sometimes it is different i think @maryjaf https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=2961-79133&t=1qCRhTsNyoIbOoAu-0

You're right 
It works as expected

![image](https://github.com/user-attachments/assets/8bd8f714-bbcd-4e4e-ac75-dbd0ca405682)
