### ISSUE TITLE
[Feedback] It seems there is a problem in calculating percentage of project

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-rf6#178]
### What happened?

I only rated two projects , remix project and ethereumjs monoreport(first video), for the other pairwise I tap on "skip" button but I see below result (second video)

https://github.com/user-attachments/assets/e0595987-c19b-4949-b640-f81881fb1e37

https://github.com/user-attachments/assets/7a16de29-18ec-45b7-99f1-6e3828e507bb

@mmahdigh

**Comment by mmahdigh** [comment]
I believe It's not a bug. Only doing one pairwise and skipping the rest doesn't give the algorithm enough signal to come up with a proper ranking. It's expected.
