### ISSUE TITLE
[Feedback] UI problem on project card

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-rf6#180]
### What happened?

UI problem on project card

https://github.com/user-attachments/assets/bf2503f9-d478-48cb-a895-7f2f60654f94

cc: @mmahdigh @HrithikSampson

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/ddfbb3d9-fd06-49d8-bfd5-c4e2e6001831)

**Comment by mmahdigh** [comment]
This is fixed as well.
