### ISSUE TITLE
Pairwise Farcaster bot: Cast about delegations regularly

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rf6#21]
As a Pairwise stakeholder, I want to announce delegations on pairwise so the app is going viral and users who got delegated come and use the app. 

### Success Criteria
- [x] Bot will query the list of new delegations and the username of the user who gets delegated every 12 hours,
- [x] The query from the backend should be grouped by `delegated to` username and should contain the number of delegates people so be able to send this sample cast:

```
Hey @username 👋

Five people have delegated to you in the last 12 hours 🥳

They want you to vote on their behalf in the @Optimism Retro Funding 6 Round. Go to app.pairwise.vote and rank the projects!
```

- [x] Bot starts sending cast based on those records and marked them as sent. In order not to get blocked, bot can manage the schedule of casting itself. 
- [ ] Casts are public. 
- [x] Casts will be sent from Pairwise Farcaster's account. (@markoprljic needs to sign-off the sending account) 
- [ ] @maryjaf test cases will be added to this issue.

**Comment by GriffGreen** [comment]
oops it was too long before and the capital letters ruined the tag!

```
[@griff.eth](https://warpcast.com/griff.eth) 👋

🗳️ 1 person has delegated to you in [@pairwise](https://warpcast.com/pairwise)'s Liquid Democracy experiment!

🤝 Delegate this voting power to the [@farcaster](https://warpcast.com/farcaster) users you trust to judge projects in [@optimism](https://warpcast.com/optimism)'s Retro Funding 6 round or vote yourself! 🫡

👇 
[app.pairwise.vote](http://app.pairwise.vote/)

```

Or if that doesn't work
```
@griff.eth 👋

🗳️ 1 person has delegated to you in @pairwise's Liquid Democracy experiment!

🤝 Delegate this voting power to the @farcaster users you trust to judge projects in @optimism's Retro Funding 6 round or vote yourself! 🫡

👇 
app.pairwise.vote
```

**Comment by RamRamez** [comment]
🫡

> oops it was too long before and the capital letters ruined the tag!
> 
> ```
> [@griff.eth](https://warpcast.com/griff.eth) 👋
> 
> 🗳️ 1 person has delegated to you in [@pairwise](https://warpcast.com/pairwise)'s Liquid Democracy experiment!
> 
> 🤝 Delegate this voting power to the [@farcaster](https://warpcast.com/farcaster) users you trust to judge projects in [@optimism](https://warpcast.com/optimism)'s Retro Funding 6 round or vote yourself! 🫡
> 
> 👇 
> [app.pairwise.vote](http://app.pairwise.vote/)
> ```
> 
> Or if that doesn't work
> 
> ```
> @griff.eth 👋
> 
> 🗳️ 1 person has delegated to you in @pairwise's Liquid Democracy experiment!
> 
> 🤝 Delegate this voting power to the @farcaster users you trust to judge projects in @optimism's Retro Funding 6 round or vote yourself! 🫡
> 
> 👇 
> app.pairwise.vote
> ```

Done! (It's waiting for review)
