### ISSUE TITLE
PostHog installation

### ISSUE THREAD

**Issue by markoprljic** [GeneralMagicio/pairwise-rf6#47]
Posthog is not receiving any data from the rf5!

Please verify and re-install the Posthog on rf5.pairwise.

[https://posthog.com/docs/libraries/react](https://posthog.com/docs/libraries/react)

- [x] Create a Google Tag manager (Ahmad/Mo)
- [x] Add Posthog code to the `header` of Pairwise app (Developers)
- [x] Define user flows that we want to track (Marko/Mo)
- [x] Go through the app and define all actions (buttons) on Pairwise app where we need to add ID (Mo)
- [x] Set up insights (user flows) we want to track on Posthog (Mo)

**Comment by markoprljic** [comment]
@mosaeedi Can you please update this task, see todo list.

**Comment by MoeNick** [comment]
I moved this one to draft, I think we should define the pipeline first.

**Comment by mosaeedi** [comment]
The Posthog is installed correctly and it's working,
Now we need to attach IDs to specific elements to filter the Posthog Data.


I'll create another task to cover all IDs.
