### ISSUE TITLE
Edit the ranking of a category

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rf6#6]
As a user, I want to edit my voted category and attest again. 

### Design:
https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=1175-36543&t=YULRHcxIjN0cH8Gc-4

### Success Criteria

- [x] 1. The user sees the list of projects (like ballot) with percentages
- [x] 2. It has been sorted by high to low by default. 
- [x] 3. They can edit by locking and typing the percentages. 
- [x] 4- Percentages can be locked, Max `N-2` of them can be locked at the same time, if `N-2` is locked, the other lock icons will be disabled.
- [x] 5- when changing any % the other unlocked fields will change accordingly based on the weights they have 
- [x] 6- if the user ends up having more than 100% in summation, a toast message is shown accordingly in the summation section. 
- [ ] 7. The user can freeze percentages and only drag and drop projects in the given provided allocation. 
- [x] 8- The back button will lead the user back to the categories. 
- [x] 9. `Submit Vote` will run the attest flow #9

**Comment by maryjaf** [comment]
I got new error by taping on vote
By tapping on connect button in email  modal I redirected to the first page and I couldn't complete the ranking flow

https://github.com/user-attachments/assets/7cb57314-2d01-4037-a3b7-26b7afa5bfae

**Comment by maryjaf** [comment]
> > In the budget edit, we don't allow the user to lock more than **n-2** categories.
> > However, in the category edit, we only display an error message but still allow the user to lock the category.
> > budget:
> > Screen.Recording.2024-10-29.at.8.18.07.PM.mov
> > category:
> > Screen.Recording.2024-10-29.at.8.11.34.PM.mov
> > [@Meriem-BM](https://github.com/Meriem-BM) [@MoeNick](https://github.com/MoeNick)
> 
> [@maryjaf](https://github.com/maryjaf) you can test this one

Thanks @Meriem-BM It has been fixed

**Comment by MoeNick** [comment]
The padding issue has been resolved, but I can see some odd alignment issues for some projects
![Image](https://github.com/user-attachments/assets/d31c3d24-87ad-4879-81b5-e5c381682b2c)
![Image](https://github.com/user-attachments/assets/e33949de-2a69-490c-90c2-3a3bbe92a30f)

**Comment by MoeNick** [comment]
it's on prod, but worth to check it one more time @maryjaf
