### ISSUE TITLE
Login with email | redundant email shows 500 error

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-rf6#65]
when I set an email that it was used for other account I see 500 error in log

![image](https://github.com/user-attachments/assets/5dd9ab3f-4a36-40c2-b0e2-63d35a74ef1e)

cc: @Meriem-BM @mmahdigh

**Comment by Meriem-BM** [comment]
Can you test this @maryjaf

**Comment by maryjaf** [comment]
Great, thanks @Meriem-BM It has been fixed
