### ISSUE TITLE
Pairwise Farcaster Bot | Thank You Cast.

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rf6#66]
> BONUS POINTS!
> 
> 
> 
> Once someone has used the app and delegated or voted for all 4 options, they should stop receiving the casts, and we should send them a separate cast:
> 
> 
> 
> ```
> 
> @username thank you for playing with Pairwise! YOU ROCK!
> 
> ```
> 
>  

 _Originally posted by @GriffGreen in [#21](https://github.com/GeneralMagicio/pairwise-rf6/issues/21#issuecomment-2440105484)_

### Success Criteria:

- [ ] A delegated to B and the bot sends casts every day to B to go and use the app.
- [ ] B do all categories, (vote or delegate) then bot should send `Thank You` Cast instead of regular casts. 
- [ ] The thank you cats should be only one time.

**Comment by MoeNick** [comment]
@RamRamez can you jump into this?

**Comment by RamRamez** [comment]
I'm on it

**Comment by RamRamez** [comment]
Done! (waiting for code review and merge)

**Comment by MoeNick** [comment]
GM 
can you update me please if it's merged? 
CC: @mmahdigh

**Comment by RamRamez** [comment]
It's merged on staging. I created a PR for the release.

https://github.com/GeneralMagicio/pw-backend/pull/68

**Comment by maryjaf** [comment]
could you please tell me more about this issue and farcaster bot that I be able to test this? 
@RamRamez @mmahdigh

**Comment by RamRamez** [comment]
@maryjaf 

> It means that they have engaged with https://github.com/pairwise completely... there are 3 categories and the budget, for each of those 4 things, they can vote or delegate, if they have voted or delegated 4 times

then we will send them the cast

> @username! Thank you for playing with Pairwise!
> YOU ROCK!

with [this Farcaster account](https://warpcast.com/ramramez) on staging

**Comment by RamRamez** [comment]
@maryjaf consider this user that has delegated or voted to all 3 possible categories + budget
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/16522053-a137-4be6-af34-20518d126965">

**Comment by MoeNick** [comment]
Sorry @maryjaf I now updated the success criteria, apologies for missing this.

**Comment by maryjaf** [comment]
> * B do all categories, (vote or delegate) then bot should send `Thank You` Cast instead of regular casts.

I haven't received this cast it seems there is a problem related to cron job

**Comment by maryjaf** [comment]
> * A delegated to B and the bot sends casts every day to B to go and use the app.

Could someone please delegate to me (maryjaf)to check this  @MoeNick @RamRamez

**Comment by RamRamez** [comment]
> > * B do all categories, (vote or delegate) then bot should send `Thank You` Cast instead of regular casts.
> 
> I haven't received this cast it seems there is a problem related to cron job

@maryjaf The CI/CD is not set yet and my PR wasn't deployed. @mmahdigh deployed my PR and now it's working.
<img width="635" alt="image" src="https://github.com/user-attachments/assets/02c63013-8aec-46d6-aa7a-d062f7beb1fa">

**Comment by RamRamez** [comment]
> > * A delegated to B and the bot sends casts every day to B to go and use the app.
> 
> Could someone please delegate to me (maryjaf)to check this @MoeNick @RamRamez

Sure @maryjaf, I delegated to you

**Comment by maryjaf** [comment]
> > > * A delegated to B and the bot sends casts every day to B to go and use the app.
> > 
> > 
> > Could someone please delegate to me (maryjaf)to check this @MoeNick @RamRamez
> 
> Sure @maryjaf, I delegated to you

![IMG_5632](https://github.com/user-attachments/assets/762df886-86a0-4d91-bcd8-1da0830579e0)
