### ISSUE TITLE
[Error in login with email]| Despite connecting my email to my wallet account, the 'Connect Email' modal reappears again 

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-rf6#73]
-  I've already connected my email into my wallet account 
- if I login again by tapping on vote I see connect email modal again 

@Meriem-BM

**Comment by Meriem-BM** [comment]
Can you test this @maryjaf

**Comment by maryjaf** [comment]
Thanks @Meriem-BM It has been fixed
