### ISSUE TITLE
Budget min and max

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rf6#84]
The Foundation is assigning a minimum OP Amount for the round of 1.1M OP and a maximum OP amount of 3.5m OP.

So this view should chnage
![Image](https://github.com/user-attachments/assets/3aae37d9-1255-4fd8-aee2-ab811578621e)

**Comment by maryjaf** [comment]
by tapping on submit vote , I got an error 
budget must not be less than 2000000
@HrithikSampson 

![Image](https://github.com/user-attachments/assets/7610bbfe-75e6-4137-913c-57e27a6fd735)

**Comment by HrithikSampson** [comment]
> by tapping on submit vote , I got an error budget must not be less than 2000000 @HrithikSampson
> 
> ![Image](https://private-user-images.githubusercontent.com/111529185/381729068-7610bbfe-75e6-4137-913c-57e27a6fd735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjE0MzgsIm5iZiI6MTczMDMyMTEzOCwicGF0aCI6Ii8xMTE1MjkxODUvMzgxNzI5MDY4LTc2MTBiYmZlLTc1ZTYtNDEzNy05MTNjLTU3ZTI3YTZmZDczNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQyMDQ1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDM0Mjk4YmRiZTRhMGY4MzczZDgzNjdiNWYwM2U2ZmJjODlkZjQ2ZGE3ZTk1NTk3OWFlNDYxMTAzOTkyZTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PVoaHz3UApf_tADv6DEhnyK9ybIfA6Cp2gmbWYgh2z4)

@mmahdigh, could you check the range I have changed in frontend

**Comment by mmahdigh** [comment]
> by tapping on submit vote , I got an error budget must not be less than 2000000 @HrithikSampson
> 
> ![Image](https://private-user-images.githubusercontent.com/111529185/381729068-7610bbfe-75e6-4137-913c-57e27a6fd735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjg1MjksIm5iZiI6MTczMDM2ODIyOSwicGF0aCI6Ii8xMTE1MjkxODUvMzgxNzI5MDY4LTc2MTBiYmZlLTc1ZTYtNDEzNy05MTNjLTU3ZTI3YTZmZDczNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwOTUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTViNGJlNGZmNzU4MDM5YjNjZDExYWZjYTc0Zjc3ZjZhMjljN2E0NzM1YjRmY2IwOGJhYzkxMWQ0NDVlODdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hvfJ7VBV9zeeQCPqrZDJQpSSBn3JqI23Y_I9QNJsnPw)

This is fixed. Would you please do a retest?

**Comment by maryjaf** [comment]
Thanks @mmahdigh the previous problem has been fixes

but there is a UI problem @HrithikSampson 
now in UI the default op is 2,000,000 m 

![image](https://github.com/user-attachments/assets/b35fc010-1014-4230-8923-8729b0002e7c)

**Comment by mmahdigh** [comment]
> Hi @mmahdigh ,
> 
> the default value is also coming from the backend from `/flow/ranking`
> 
> const [totalValue, setTotalValue] = useState(categoryRankings?.budget || 0);

The default value is 2M which is fine. Isn't it?
