### ISSUE TITLE
[Error submit vote] Delegate Button  in budget allocation page Visibility and Functionality Discrepancy

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-rf6#88]
**Summary**
The delegate button appears redundantly in two locations, which creates confusion in the user experience. Additionally, in some cases, tapping the delegate button has no effect.

**Steps to Reproduce**

Navigate to the Budget Allocation page 
Notice the Delegate button displayed on this page.
Tap on delegate button 

**Observed Behavior**
The Delegate button appears in both the Budget Allocation and main allocation pages.
The button on the Budget Allocation page is non-functional when tapped.
After submitting a vote, the Delegate button disappears from the Allocation page but remains on the budget allocation page.

**Expected Behavior**
Option A: Remove the Delegate button from the Budget Allocation page, keeping it only on the main allocation page.
Option B: Ensure that the Delegate button functions properly on both pages and appears consistently after a vote is submitted.

https://github.com/user-attachments/assets/9ceda955-accc-4386-98b3-86c94846bea5

https://github.com/user-attachments/assets/e4968aff-fe2f-49f9-a6b2-5c9ad71b93de

**Comment by Meriem-BM** [comment]
@HrithikSampson removed it, you can check @maryjaf

**Comment by maryjaf** [comment]
Yes, it's removed thanks
